### ISSUE TITLE
Add Assembly language?

### ISSUE THREAD

**Issue by ghost** [ICBIPL/Fibonacci#9] opened 2020-03-27 12:13 UTC
Currently none of the contributors have contributed an Assembly language program. Given that I don't know how to program in Assembly language, I'd be glad to see an Assembly language implementation.

**Comment by KaiLyons** [comment] 2020-03-28 18:24
I have been looking into it, it is a long and pretty hard process to do and it will take a good amount of time.

**Comment by xhebox** [comment] 2020-03-29 10:12
If you allow the program link to printf & scanf in libc.so, it is not so hard. But the problem is that assembly itself is ISA-specific, OS-specific and ABI-spefic. You will have to write different versions for every platform. You can refer to [rosetta code](https://rosettacode.org/wiki/Fibonacci_sequence) for some codes. Maybe inline-asm is a good choice for your purpose.

Here is an implementation for x86-64 linux:

```asm
        .intel_syntax noprefix
        .global    main
        .extern    printf

        .text
main:
        push      rdi
        mov       r12, 0
        mov       r13, 1
        mov       r14, 0

loop:
        lea       rdi, formatstr
        mov       rsi, r12
        call      printf

        lea       rdi, formatstr
        mov       rsi, r13
        call      printf

        lea       r12, [r12+r13]
        lea       r13, [r12+r13]

        inc       r14
        cmp       r14, 1000001
        jle       loop

        pop       rdi
        ret

formatstr:
        .asciz    "%llu\n"
```

Just `gcc -no-pie test.S` and here it is. And even `%llu` precision is not enough, same to your `%d` C [implementation](https://github.com/Random-People/Fibonacci/blob/master/fib.c).

**EDIT**: No offense, just some comments. I do not see much practical sense on the current goal of this project, it looks like a just-for-fun project. And there are lots of projects/websites aiming at algorithm implementation collections. I would suggest something different, e.g. benchmarks. Or integrate with an online compiler just like godbolt.org.

**Comment by loralighte** [comment] 2020-04-01 06:02
We made it, close it?

**Closed as completed** 2020-04-01 13:04 UTC
